# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 595)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.accountsTree = QtWidgets.QTreeView(self.centralWidget)
        self.accountsTree.setObjectName("accountsTree")
        self.horizontalLayout_2.addWidget(self.accountsTree)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.transactionTable = QtWidgets.QTableView(self.centralWidget)
        self.transactionTable.setObjectName("transactionTable")
        self.verticalLayout.addWidget(self.transactionTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addTransaction = QtWidgets.QPushButton(self.centralWidget)
        self.addTransaction.setObjectName("addTransaction")
        self.horizontalLayout.addWidget(self.addTransaction)
        self.editTransaction = QtWidgets.QPushButton(self.centralWidget)
        self.editTransaction.setObjectName("editTransaction")
        self.horizontalLayout.addWidget(self.editTransaction)
        self.copyTransaction = QtWidgets.QPushButton(self.centralWidget)
        self.copyTransaction.setObjectName("copyTransaction")
        self.horizontalLayout.addWidget(self.copyTransaction)
        self.deleteTransaction = QtWidgets.QPushButton(self.centralWidget)
        self.deleteTransaction.setObjectName("deleteTransaction")
        self.horizontalLayout.addWidget(self.deleteTransaction)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 988, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuManage = QtWidgets.QMenu(self.menuBar)
        self.menuManage.setObjectName("menuManage")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionManageAccounts = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dollar178.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManageAccounts.setIcon(icon)
        self.actionManageAccounts.setObjectName("actionManageAccounts")
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/door24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenFile.setIcon(icon1)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionNewFile = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconset/iconset/svg/add189.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewFile.setIcon(icon2)
        self.actionNewFile.setObjectName("actionNewFile")
        self.actionCloseFile = QtWidgets.QAction(MainWindow)
        self.actionCloseFile.setObjectName("actionCloseFile")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionManageCategories = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/bookmark49.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManageCategories.setIcon(icon3)
        self.actionManageCategories.setObjectName("actionManageCategories")
        self.actionBudget = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/left225.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBudget.setIcon(icon4)
        self.actionBudget.setObjectName("actionBudget")
        self.menuFile.addAction(self.actionNewFile)
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionCloseFile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuManage.addAction(self.actionManageAccounts)
        self.menuManage.addAction(self.actionManageCategories)
        self.menuManage.addAction(self.actionBudget)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuManage.menuAction())
        self.mainToolBar.addAction(self.actionOpenFile)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionManageAccounts)
        self.mainToolBar.addAction(self.actionManageCategories)
        self.mainToolBar.addAction(self.actionBudget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Budget"))
        self.addTransaction.setText(_translate("MainWindow", "Add"))
        self.editTransaction.setText(_translate("MainWindow", "Edit"))
        self.copyTransaction.setText(_translate("MainWindow", "Copy"))
        self.deleteTransaction.setText(_translate("MainWindow", "Delete"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuManage.setTitle(_translate("MainWindow", "Manage"))
        self.actionManageAccounts.setText(_translate("MainWindow", "Accounts"))
        self.actionManageAccounts.setToolTip(_translate("MainWindow", "Accounts"))
        self.actionOpenFile.setText(_translate("MainWindow", "Open a file"))
        self.actionNewFile.setText(_translate("MainWindow", "New file"))
        self.actionCloseFile.setText(_translate("MainWindow", "Close file"))
        self.actionCloseFile.setToolTip(_translate("MainWindow", "Close file"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionManageCategories.setText(_translate("MainWindow", "Categories"))
        self.actionManageCategories.setToolTip(_translate("MainWindow", "Categories"))
        self.actionBudget.setText(_translate("MainWindow", "Budget"))

import ui.iconset_rc
